// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm5qShUuDX1AUE6v2HcAeHTPXnoSCKNFk',
    appId: '1:288025315207:web:39c5335af36e26b285b522',
    messagingSenderId: '288025315207',
    projectId: 'apoyo-emocional-ia-app',
    authDomain: 'apoyo-emocional-ia-app.firebaseapp.com',
    storageBucket: 'apoyo-emocional-ia-app.firebasestorage.app',
    measurementId: 'G-J9RR1QMSQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUIrGdY0SNfc2L1KV_7KSwXJjPhI6qQ1M',
    appId: '1:288025315207:android:3b87a10b899513e085b522',
    messagingSenderId: '288025315207',
    projectId: 'apoyo-emocional-ia-app',
    storageBucket: 'apoyo-emocional-ia-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTrVsEXgK8-IqAKCdAUyXQJMuB8SU9p3k',
    appId: '1:288025315207:ios:023642d51c82973185b522',
    messagingSenderId: '288025315207',
    projectId: 'apoyo-emocional-ia-app',
    storageBucket: 'apoyo-emocional-ia-app.firebasestorage.app',
    iosBundleId: 'com.example.apoyoEmocionalIaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTrVsEXgK8-IqAKCdAUyXQJMuB8SU9p3k',
    appId: '1:288025315207:ios:023642d51c82973185b522',
    messagingSenderId: '288025315207',
    projectId: 'apoyo-emocional-ia-app',
    storageBucket: 'apoyo-emocional-ia-app.firebasestorage.app',
    iosBundleId: 'com.example.apoyoEmocionalIaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm5qShUuDX1AUE6v2HcAeHTPXnoSCKNFk',
    appId: '1:288025315207:web:4d7104cd2c1ced1a85b522',
    messagingSenderId: '288025315207',
    projectId: 'apoyo-emocional-ia-app',
    authDomain: 'apoyo-emocional-ia-app.firebaseapp.com',
    storageBucket: 'apoyo-emocional-ia-app.firebasestorage.app',
    measurementId: 'G-J98KB55JBY',
  );
}
